### ISSUE TITLE
MIME types demystified

### ISSUE THREAD

**Issue by Rowno** [Rowno/roland.codes#12]
This issue is reserved for blog post comments. All comments on this issue and will appear on the [blog post's web page](https://roland.codes/blog/mime-types-demystified/).

**Comment by sukima** [comment]
`type/x-whatever` is for *unregistered* or *experimental* while the `type/prs.whatever` is for *personal* or *vanity*. While that makes sense from a gramatical/vocabulary perspective when it comes to making a type of your own that you plan to use for your own application it leads little information on which one is most appropiot. Sadly, a Google search yields the same basic definitions and no guidance on which one to pick.

Do you know what the contextual difference between those two are?

**Comment by Rowno** [comment]
Sorry, I have no idea. :smile: But I'm guessing that with the `x-` prefix the intention is to eventually get it added to the standard like what happened with the WOFF mime type, which started life as `application/x-font-woff` and then got standardised as `application/font-woff`.
