### ISSUE TITLE
Make Sublime Text 2 treat script tag templates as HTML

### ISSUE THREAD

**Issue by Rowno** [Rowno/roland.codes#17]
This issue is reserved for blog post comments. All comments on this issue and will appear on the [blog post's web page](https://roland.codes/blog/sublime-text-2-script-tag-templates/).

**Comment by sciascia** [comment]
Hi There, 

Does anyone know how to fix this issue in ST3 on Mac OS10.9? 

There are no ```HTML.tmLanguage ``` files if I go ```Preferences -> Browse Packages…```. 

If I ```Show package contents``` on the Sublime Text app then go ```Contents –> MacOS –> Packages``` I can see a file called ```HTML.sublime-package``` but it looks to be some sort of compressed archive that can't be edited.

If I search the system (including system files) for ```HTML.tmLanguage```` all that's returned is a cache file named ```HTML.tmLanguage.cache``` and a python file named ```sublimezenplugin.py```.

Any pointers in the right direction would be much appreciated.

Cheers

Ben

**Comment by Rowno** [comment]
@sciascia The default packages are no longer extracted into the user Packages directory in Sublime Text 3. 

Here's what you need to do:

1. Copy `Packages/HTML.sublime-package` file from the installation directory and decompress it as a `.zip` file (rename it to `HTML.sublime-package.zip`).
2. Copy the `HTML.tmLanguage` file inside to `HTML/HTML.tmLanguage` in your user Packages directory (ie: `Preferences -> Browse Packages…`).
3. Edit the `HTML.tmLanguage` file to make the required change at line 308.
4. Profit. :sparkles:

Maybe I should write a followup blog post. :wink:

**Comment by sciascia** [comment]
@Rowno Cheers, thanks heaps for the reply and your help.

I'd just installed SublimeLinter which seemed to install it's own version of ```HTML.tmLanguage``` and fixed the issue. 

BTW I was having this issue with straight js script tags (no type) but have now noticed that js syntax highlighting doesn't work. I guess it's an either/or situation yes?

**Comment by Rowno** [comment]
@sciascia No, both are working fine for me.

**Comment by nivincp** [comment]
couldn't get none of these working for me in macos sierra.. ended up setting up the syntax as xml :-)
