### ISSUE TITLE
IE flex collapse bug

### ISSUE THREAD

**Issue by Rowno** [Rowno/roland.codes#20]
This issue is reserved for blog post comments. All comments on this issue and will appear on the [blog post's web page](https://roland.codes/blog/ie-flex-collapse-bug/).

**Comment by scotato** [comment]
Very helpful, thanks!

**Comment by WoollyMittens** [comment]
That's great! It saved me hours.

**Comment by mmanneva** [comment]
This got me out of trouble, thanks!

**Comment by pierrea** [comment]
Alleluia. Thank you

**Comment by antony** [comment]
Thanks! You inspired a tweet https://twitter.com/antony/status/1283379123398881282
