### ISSUE TITLE
Legacy flexbox invisible float bug

### ISSUE THREAD

**Issue by Rowno** [Rowno/roland.codes#21]
This issue is reserved for blog post comments. All comments on this issue and will appear on the [blog post's web page](https://roland.codes/blog/legacy-flexbox-invisible-float-bug/).

**Comment by jmcguerreiro** [comment]
Thank you for sharing the fix. Couldn't really find a lot of info regarding this issue.

**Comment by johnwade47** [comment]
Thank you so much for this fix! It was driving me crazy.

**Comment by dracos** [comment]
Thanks, we just came across this with a Safari 5 user being unable to see some flexbox radio icons we were using.
